version: "3.9"

services:
  evebox:
    image: jasonish/evebox:master
    container_name: evebox
    ports:
      - "5636:5636"
    volumes:
      - ./data/suricata/log:/var/log/suricata
      - ./config/evebox/server:/config
      - ./data/evebox/server:/data
    command: >
      evebox server --no-tls --host=[::0] --sqlite
      --data-directory=/data
      --config-directory=/config
      /var/log/suricata/eve.json
    restart: unless-stopped

  suricata:
    image: jasonish/suricata:latest
    container_name: suricata
    network_mode: host
    cap_add:
      - SYS_NICE
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ./config/af-packet.yaml:/config/af-packet.yaml
      - ./data/suricata/log:/var/log/suricata
      - ./config/suricata/lib:/var/lib/suricata
      - ./data/suricata/run:/var/run/suricata
      -  /etc/suricata:/etc/suricata
    command: >
      -v -i lo --include /config/af-packet.yaml
      --set sensor-name=as
    restart: unless-stopped
